<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Group_11_Analysis</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Group_11_Analysis_files/libs/clipboard/clipboard.min.js"></script>
<script src="Group_11_Analysis_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="Group_11_Analysis_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="Group_11_Analysis_files/libs/quarto-html/popper.min.js"></script>
<script src="Group_11_Analysis_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Group_11_Analysis_files/libs/quarto-html/anchor.min.js"></script>
<link href="Group_11_Analysis_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Group_11_Analysis_files/libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Group_11_Analysis_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Group_11_Analysis_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Group_11_Analysis_files/libs/bootstrap/bootstrap-bb462d781dde1847d9e3ccf7736099dd.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="Group_11_Analysis_files/libs/kePrint-0.0.1/kePrint.js"></script>

<link href="Group_11_Analysis_files/libs/lightable-0.0.1/lightable.css" rel="stylesheet">



</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Group_11_Analysis</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="eda-part" class="level1">
<h1>EDA Part</h1>
<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>Coffee quality is a key link connecting producer profits and consumer experience. It not only directly determines market value, but also affects the sustainable development of the coffee industry. This study relies on the real production records of the Coffee Quality Database (CQD), focusing on the three core sensory indicators of aroma, flavor, and acidity, as well as key production characteristics such as the number of category_tow_defects, average planting altitude, and harvest year. We conducted a systematic exploratory analysis of the data and constructed a generalized linear model (GLM), which clearly revealed the direction and strength of the impact of each feature on coffee quality classification. The research results provide guidance for producers to help improve coffee quality.</p>
<p>We systematically processed the original coffee dataset to ensure the reliability of subsequent modeling and analysis.</p>
<p>Firstly, we check the data structure and missing values, and remove invalid samples with missing key variables. Then, outlier screening was performed on the average altitude. Through visualization, it was found that there were two extreme values exceeding 100000 meters, which obviously do not match the actual coffee cultivation and have been removed. Further examination through histograms and boxplots revealed that there were 12 extreme samples with elevations exceeding 2500 meters, which were also deleted.</p>
<p>In order to standardize the numerical scale, we converted the average altitude from meters to kilometers. Subsequently, unnecessary columns were removed and the coffee quality variable was converted into a factor variable.</p>
</section>
<section id="exploratory-analysis" class="level2">
<h2 class="anchored" data-anchor-id="exploratory-analysis">Exploratory Analysis</h2>
<div class="cell">
<div id="tbl-description-of-Qualityclass" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-description-of-Qualityclass-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Description of Qualityclass
</figcaption>
<div aria-describedby="tbl-description-of-Qualityclass-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table do-not-create-environment cell caption-top table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: center;" data-quarto-table-cell-role="th">Variable</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Category</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Frequency</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Qualityclass</td>
<td style="text-align: center;">Poor</td>
<td style="text-align: center;">436</td>
</tr>
<tr class="even">
<td style="text-align: center;">Qualityclass</td>
<td style="text-align: center;">Good</td>
<td style="text-align: center;">444</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p><a href="#tbl-description-of-Qualityclass" class="quarto-xref">Table&nbsp;1</a> shows the frequency of categorical variable. The variable Qualityclass is a binary categorical variable, consisting of two levels: “Good” (high-quality coffee) and “Poor” (low-quality coffee). The sample distribution is highly balanced, with 444 high-quality coffee samples (accounting for 50.5%) and 436 low-quality coffee samples (accounting for 49.5%). There is no problem of category imbalance, which can ensure the stability of subsequent models.</p>
<div class="cell">
<div id="tbl-summary-of-quantitative-variables" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-summary-of-quantitative-variables-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: summary of quantitative variables
</figcaption>
<div aria-describedby="tbl-summary-of-quantitative-variables-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table do-not-create-environment cell caption-top table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: center;" data-quarto-table-cell-role="th">Variable</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Mean</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Median</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">SD</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Min</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Max</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">IQR</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">aroma</td>
<td style="text-align: center;">7.57</td>
<td style="text-align: center;">7.58</td>
<td style="text-align: center;">0.32</td>
<td style="text-align: center;">5.08</td>
<td style="text-align: center;">8.75</td>
<td style="text-align: center;">0.33</td>
</tr>
<tr class="even">
<td style="text-align: center;">flavor</td>
<td style="text-align: center;">7.52</td>
<td style="text-align: center;">7.58</td>
<td style="text-align: center;">0.33</td>
<td style="text-align: center;">6.17</td>
<td style="text-align: center;">8.83</td>
<td style="text-align: center;">0.42</td>
</tr>
<tr class="odd">
<td style="text-align: center;">acidity</td>
<td style="text-align: center;">7.54</td>
<td style="text-align: center;">7.50</td>
<td style="text-align: center;">0.31</td>
<td style="text-align: center;">5.25</td>
<td style="text-align: center;">8.75</td>
<td style="text-align: center;">0.42</td>
</tr>
<tr class="even">
<td style="text-align: center;">category_two_defects</td>
<td style="text-align: center;">3.51</td>
<td style="text-align: center;">2.00</td>
<td style="text-align: center;">5.24</td>
<td style="text-align: center;">0.00</td>
<td style="text-align: center;">45.00</td>
<td style="text-align: center;">4.00</td>
</tr>
<tr class="odd">
<td style="text-align: center;">harvested</td>
<td style="text-align: center;">2013.70</td>
<td style="text-align: center;">2014.00</td>
<td style="text-align: center;">1.81</td>
<td style="text-align: center;">2010.00</td>
<td style="text-align: center;">2018.00</td>
<td style="text-align: center;">3.00</td>
</tr>
<tr class="even">
<td style="text-align: center;">altitude_km</td>
<td style="text-align: center;">1.30</td>
<td style="text-align: center;">1.31</td>
<td style="text-align: center;">0.41</td>
<td style="text-align: center;">0.00</td>
<td style="text-align: center;">2.14</td>
<td style="text-align: center;">0.50</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p><a href="#tbl-summary-of-quantitative-variables" class="quarto-xref">Table&nbsp;2</a> shows the descriptive statistics of the key quantitative variables of coffee samples, including three sensory quality indicators, one defect count indicator, one harvest year indicator and one indicator of average planting altitude.</p>
<p>Aroma scores fall in a moderate-to-high range with a mean value of 7.57 and a median value of 7.58, indicating a highly similar distribution. The standard deviation is only 0.32, with minimal fluctuations, indicating that there is not much difference in aroma scores between samples, and the overall concentration is at a relatively high level.</p>
<p>Flavor scores is Similar to the aroma performance, which remains stable and concentrated at a medium to high level.</p>
<p>Acidity also maintains a moderate-to-high scoring level, with a mean of 7.54 and a median of 7.58, while the standard deviation is 0.31, which is the smallest fluctuation among the three sensory indicators, indicating that acidity is the most stable performance.</p>
<p>The mean number of category_tow_defects is 3.51, but the median is only 2.00, the standard deviation is as high as 5.24 and the maximum value reaches 45.00, indicating a significant right bias in the data. Most samples have fewer defects, but there are a few extreme samples with extremely many defects.</p>
<p>The harvest years are concentrated between 2010 and 2018, with a standard deviation of 1.81, indicating a small sample time span and compact year distribution.</p>
<p>The average altitude is 1.30km, the median is 1.31km, and the distribution is approximately symmetrical. The standard deviation is 0.41, with a maximum value of 2.14km and a minimum value of 0.00km, indicating that the sample covers coffee planting areas from low to high altitudes, and is generally concentrated at a suitable planting height of around 1.3km.</p>
<p>In summary, the mean and median of the three sensory indicators are close, the standard deviation and IQR are small, and the distribution is symmetrical and concentrated. The categorization shows a right skewed feature.</p>
<p>The above is a descriptive statistical summary of the research data. Based on this, visual analysis is used to further visualize the distribution patterns and data characteristics of each variable.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-pairplot" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-pairplot-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Group_11_Analysis_files/figure-html/fig-pairplot-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-pairplot-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: pair plot of variables
</figcaption>
</figure>
</div>
</div>
</div>
<p>This pair plot comprehensively presents the distribution and correlations of these variables.</p>
<p>The diagonal density curve shows that the three sensory indicators of aroma, flavor, and acidity exhibit an approximately symmetrical unimodal distribution. There is a double peak in the harvest year. The number of category_two_defects exhibits a clear right skewed long tail feature.</p>
<p>The correlation coefficients between aroma, flavor, and acidity are all above 0.6, indicating a strong positive correlation among the three. The average altitude is weakly positively correlated with sensory indicators, while the defects is weakly negatively correlated with sensory indicators Overall, there may be collinearity issues within sensory indicators.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-boxplot-sensory-quality-indicators" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-boxplot-sensory-quality-indicators-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Group_11_Analysis_files/figure-html/fig-boxplot-sensory-quality-indicators-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-boxplot-sensory-quality-indicators-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Boxolot of aroma,flavor and acidity
</figcaption>
</figure>
</div>
</div>
</div>
<p>This set of boxplots clearly shows the distribution differences between high-quality and low-quality coffee in three sensory indicators. The aroma, flavor, and acidity scores of high-quality coffee are generally higher, and the data is more concentrated and stable. Low quality coffee has lower scores, greater fluctuations, and more outliers in low scores. The characteristics of the two sets of outliers are also significantly different, with higher values in the high-quality group and lower values in the low-quality group. Overall, these sensory indicators can effectively distinguish coffee quality and provide intuitive basis for subsequent statistical analysis.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-histogram-altitude" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-histogram-altitude-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Group_11_Analysis_files/figure-html/fig-histogram-altitude-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-histogram-altitude-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: histogram of altitude_km
</figcaption>
</figure>
</div>
</div>
</div>
<p><a href="#fig-histogram-altitude" class="quarto-xref">Figure&nbsp;3</a> performs that altitude distribution of coffee of different qualities shows significant differences. High quality samples are mainly concentrated at altitudes of 1.5-1.8 kilometers, while low-quality samples are more concentrated at altitudes of 1.0-1.3 kilometers, with an overall bias towards low altitudes. The proportion of high-quality coffee is higher in high-altitude (&gt;1.5 kilometers) areas, while the frequency of low-quality coffee is higher in low altitude (&lt;1.2 kilometers) areas. This indicates that the higher the altitude, the more likely the coffee quality is to improve, providing intuitive evidence for the positive correlation between altitude and coffee quality.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-histogram-defects" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-histogram-defects-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Group_11_Analysis_files/figure-html/fig-histogram-defects-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-histogram-defects-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: histogram of defects
</figcaption>
</figure>
</div>
</div>
</div>
<p><a href="#fig-histogram-defects" class="quarto-xref">Figure&nbsp;4</a> shows the distribution of the number of category_two_defects in coffee of different qualities varies significantly. Overall, the number of defects shows a right skewed distribution, with most samples concentrated in the low range of 0-5 defects, and a peak formed on the left side. High quality coffee is almost entirely concentrated on 0-5 defects, and as the number of defects increases, the sample frequency rapidly decreases. In contrast, low-quality coffee has a wider distribution of defects, with samples containing 0-10 defects, and a significantly higher number of high defect segments. This difference clearly indicates that the number of defects can effectively distinguish coffee quality, and samples with fewer defects are more likely to belong to the high-quality group.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-bar-harvested" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-bar-harvested-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Group_11_Analysis_files/figure-html/fig-bar-harvested-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-bar-harvested-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: harvested stacked percentage bar plot
</figcaption>
</figure>
</div>
</div>
</div>
<p><a href="#fig-bar-harvested" class="quarto-xref">Figure&nbsp;5</a> shows the proportion distribution of coffee quality in each year from 2010 to 2018. From the plot, it can be seen that the quality of coffee fluctuates greatly in different years and lacks a stable trend. For example, in 2011, high-quality coffee accounted for about 75%, while in 2012, low-quality coffee exceeded 60%. This indicates that the harvest year has little to do with coffee quality and has limited impact on predicting quality.</p>
<p>Exploratory analysis focuses on multidimensional visualization of coffee quality related variables, clarifying the direction of variable selection for subsequent modeling.</p>
</section>
</section>
<section id="fda-part" class="level1">
<h1>FDA Part</h1>
</section>
<section id="initial-logistic-regression-model" class="level1">
<h1>Initial logistic regression model</h1>
<div class="cell" data-tbl-cap="coefficient of full model">
<div class="cell-output-display">
<table class="table caption-top table-sm table-striped small" data-quarto-postprocess="true">
<caption>coefficient of full model</caption>
<thead>
<tr class="header">
<th style="text-align: center;" data-quarto-table-cell-role="th">Term</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Estimate</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Std. Error</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">z value</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">p value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">(Intercept)</td>
<td style="text-align: center;">-475.110</td>
<td style="text-align: center;">126.077</td>
<td style="text-align: center;">-3.768</td>
<td style="text-align: center;">0.000</td>
</tr>
<tr class="even">
<td style="text-align: center;">aroma</td>
<td style="text-align: center;">4.756</td>
<td style="text-align: center;">0.722</td>
<td style="text-align: center;">6.591</td>
<td style="text-align: center;">0.000</td>
</tr>
<tr class="odd">
<td style="text-align: center;">flavor</td>
<td style="text-align: center;">7.175</td>
<td style="text-align: center;">0.876</td>
<td style="text-align: center;">8.193</td>
<td style="text-align: center;">0.000</td>
</tr>
<tr class="even">
<td style="text-align: center;">acidity</td>
<td style="text-align: center;">3.805</td>
<td style="text-align: center;">0.687</td>
<td style="text-align: center;">5.535</td>
<td style="text-align: center;">0.000</td>
</tr>
<tr class="odd">
<td style="text-align: center;">category_two_defects</td>
<td style="text-align: center;">0.019</td>
<td style="text-align: center;">0.029</td>
<td style="text-align: center;">0.677</td>
<td style="text-align: center;">0.499</td>
</tr>
<tr class="even">
<td style="text-align: center;">altitude_km</td>
<td style="text-align: center;">0.809</td>
<td style="text-align: center;">0.279</td>
<td style="text-align: center;">2.898</td>
<td style="text-align: center;">0.004</td>
</tr>
<tr class="odd">
<td style="text-align: center;">harvested</td>
<td style="text-align: center;">0.176</td>
<td style="text-align: center;">0.062</td>
<td style="text-align: center;">2.855</td>
<td style="text-align: center;">0.004</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>A binomial GLM with logit link was fitted to investigate how sensory attributes, defect counts, altitude groups and harvest year influence the probability of a coffee batch being classified as good quality.</p>
<p>To assess whether the predictors included in the initial logistic regression model exhibit problematic multicollinearity, Variance Inflation Factors (VIFs) were calculated. This is particularly relevant because the exploratory analysis suggested relatively strong positive correlations among aroma, flavor and acidity.</p>
</section>
<section id="model-selection" class="level1">
<h1>Model selection</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># stepwise selecting model via AIC</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>null_model <span class="ot">&lt;-</span> <span class="fu">glm</span>(Qualityclass <span class="sc">~</span> <span class="dv">1</span>,</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>                  <span class="at">data =</span> coffeedata,</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>                  <span class="at">family =</span> binomial)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>step_model <span class="ot">&lt;-</span> <span class="fu">step</span>(null_model, </span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>                   <span class="at">scope =</span> <span class="fu">list</span>(<span class="at">lower =</span> null_model, <span class="at">upper =</span> model_full),</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>                   <span class="at">direction =</span> <span class="st">"both"</span>,</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>                   <span class="at">trace =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Start:  AIC=1221.87
Qualityclass ~ 1

                       Df Deviance     AIC
+ flavor                1   641.37  645.37
+ aroma                 1   767.78  771.78
+ acidity               1   782.03  786.03
+ altitude_km           1  1179.97 1183.97
+ category_two_defects  1  1205.50 1209.50
&lt;none&gt;                     1219.87 1221.87
+ harvested             1  1218.04 1222.04

Step:  AIC=645.37
Qualityclass ~ flavor

                       Df Deviance     AIC
+ aroma                 1   569.75  575.75
+ acidity               1   590.91  596.91
+ altitude_km           1   621.54  627.54
&lt;none&gt;                      641.37  645.37
+ harvested             1   640.09  646.09
+ category_two_defects  1   641.33  647.33
- flavor                1  1219.87 1221.87

Step:  AIC=575.75
Qualityclass ~ flavor + aroma

                       Df Deviance    AIC
+ acidity               1   530.15 538.15
+ altitude_km           1   560.70 568.70
+ harvested             1   562.90 570.90
&lt;none&gt;                      569.75 575.75
+ category_two_defects  1   569.62 577.62
- aroma                 1   641.37 645.37
- flavor                1   767.78 771.78

Step:  AIC=538.15
Qualityclass ~ flavor + aroma + acidity

                       Df Deviance    AIC
+ altitude_km           1   523.79 533.79
+ harvested             1   524.48 534.48
&lt;none&gt;                      530.15 538.15
+ category_two_defects  1   529.79 539.79
- acidity               1   569.75 575.75
- aroma                 1   590.91 596.91
- flavor                1   616.79 622.79

Step:  AIC=533.79
Qualityclass ~ flavor + aroma + acidity + altitude_km

                       Df Deviance    AIC
+ harvested             1   515.73 527.73
&lt;none&gt;                      523.79 533.79
+ category_two_defects  1   523.59 535.59
- altitude_km           1   530.15 538.15
- acidity               1   560.70 568.70
- aroma                 1   576.02 584.02
- flavor                1   613.44 621.44

Step:  AIC=527.73
Qualityclass ~ flavor + aroma + acidity + altitude_km + harvested

                       Df Deviance    AIC
&lt;none&gt;                      515.73 527.73
+ category_two_defects  1   515.26 529.26
- harvested             1   523.79 533.79
- altitude_km           1   524.48 534.48
- acidity               1   550.98 560.98
- aroma                 1   573.18 583.18
- flavor                1   604.18 614.18</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(step_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = Qualityclass ~ flavor + aroma + acidity + altitude_km + 
    harvested, family = binomial, data = coffeedata)

Coefficients:
              Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept) -467.46783  125.38385  -3.728 0.000193 ***
flavor         7.15498    0.87780   8.151 3.61e-16 ***
aroma          4.74805    0.72293   6.568 5.11e-11 ***
acidity        3.78935    0.68760   5.511 3.57e-08 ***
altitude_km    0.81379    0.27869   2.920 0.003499 ** 
harvested      0.17277    0.06147   2.811 0.004940 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 1219.87  on 879  degrees of freedom
Residual deviance:  515.73  on 874  degrees of freedom
AIC: 527.73

Number of Fisher Scoring iterations: 7</code></pre>
</div>
</div>
</section>
<section id="multicollinearity-check" class="level1">
<h1>Multicollinearity check</h1>
<div class="cell">
<div class="cell-output-display">
<table class="table caption-top table-sm table-striped small" data-quarto-postprocess="true">
<caption>Variance Inflation Factors for the initial logistic regression model</caption>
<thead>
<tr class="header">
<th style="text-align: center;" data-quarto-table-cell-role="th">Variable</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">VIF</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">flavor</td>
<td style="text-align: center;">1.097</td>
</tr>
<tr class="even">
<td style="text-align: center;">aroma</td>
<td style="text-align: center;">1.074</td>
</tr>
<tr class="odd">
<td style="text-align: center;">acidity</td>
<td style="text-align: center;">1.056</td>
</tr>
<tr class="even">
<td style="text-align: center;">altitude_km</td>
<td style="text-align: center;">1.076</td>
</tr>
<tr class="odd">
<td style="text-align: center;">harvested</td>
<td style="text-align: center;">1.090</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Table X presents the VIF values for all predictors included in the initial model. Overall, the sensory variables show comparatively larger VIF values than the remaining predictors, which is consistent with the correlation patterns observed in the exploratory analysis. These results suggest that multicollinearity should be taken into account in subsequent model refinement.</p>
</section>
<section id="visualising-model-fit" class="level1">
<h1>Visualising model fit</h1>
<section id="fitted-probability-vs-observed" class="level2">
<h2 class="anchored" data-anchor-id="fitted-probability-vs-observed">Fitted Probability vs Observed</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>coffeedata<span class="sc">$</span>pred_prob <span class="ot">&lt;-</span> <span class="fu">predict</span>(step_model, <span class="at">type =</span> <span class="st">"response"</span>)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(coffeedata, <span class="fu">aes</span>(<span class="at">x =</span> pred_prob, <span class="at">y =</span> <span class="fu">factor</span>(Qualityclass))) <span class="sc">+</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">height =</span> <span class="fl">0.1</span>, <span class="at">alpha =</span> <span class="fl">0.4</span>) <span class="sc">+</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Predicted probability vs observed coffee quality"</span>,</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Predicted probability of good coffee"</span>,</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Observed quality class"</span></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Group_11_Analysis_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="residual-plot" class="level2">
<h2 class="anchored" data-anchor-id="residual-plot">Residual Plot</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>res <span class="ot">&lt;-</span> <span class="fu">residuals</span>(step_model, <span class="at">type =</span> <span class="st">"deviance"</span>)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">&lt;-</span> <span class="fu">fitted</span>(step_model)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">data.frame</span>(fit, res), <span class="fu">aes</span>(<span class="at">x =</span> fit, <span class="at">y =</span> res)) <span class="sc">+</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.4</span>) <span class="sc">+</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Deviance residuals vs fitted values"</span>,</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Fitted probability"</span>,</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Deviance residuals"</span></span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using method = 'loess' and formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Group_11_Analysis_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="interpretation-of-model-coefficients" class="level1">
<h1>Interpretation of model coefficients</h1>
<section id="odds-ratio" class="level2">
<h2 class="anchored" data-anchor-id="odds-ratio">Odds ratio</h2>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Group_11_Analysis_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>